name: CI Pipeline for Spring Boot with PostgreSQL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: clean-code-ci-cd
  DOCKER_IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Build Docker image
      uses: docker/build-push-action@v2 
      with:
        context: .
        image: docker-hub-repo/$DOCKER_IMAGE_NAME
        registry: docker.io
        tags: $GITHUB_REPOSITORY:$DOCKER_IMAGE_TAG
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn test
